# Generated by Django 4.1.7 on 2023-05-06 19:03

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_author_date_birth_alter_author_date_death'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='year',
            field=models.IntegerField(validators=[api.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_birth',
            field=models.CharField(max_length=100, validators=[api.models.not_current_date]),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100, validators=[api.models.validate_first]),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='name',
            field=models.CharField(max_length=100, validators=[api.models.validate_first]),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=100, validators=[api.models.validate_first]),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(max_length=100, validators=[api.models.validate_first]),
        ),
    ]
